export const eventosDomingo = [
  {
    title: 'Café da manhã',
    hourStart: '08:00',
    hourEnd: '09:40',
    period: 'Manhã',
    location: 'Restaurante',
  },
  {
    title: 'Fogo no pavio',
    hourStart: '09:40',
    hourEnd: '09:45',
    period: 'Manhã',
    location: 'Nave',
    responsible: 'TBD',
  },
  {
    title: 'Louvor',
    hourStart: '09:45',
    hourEnd: '10:15',
    period: 'Manhã',
    location: 'Nave',
    responsible: 'Ministério louvor',
  },
  {
    title: 'Ministração',
    hourStart: '10:15',
    hourEnd: '12:00',
    period: 'Manhã',
    location: 'Nave',
    responsible: 'Pr. Marcos',
  },
  {
    title: 'Almoço',
    hourStart: '12:00',
    hourEnd: '13:30',
    period: 'Tarde',
    location: 'Restaurante',
  },
  {
    title: 'LIVRE',
    hourStart: '13:30',
    hourEnd: '19:00',
    period: 'Tarde',
  },
  {
    title: 'Jantar',
    hourStart: '19:00',
    hourEnd: '20:30',
    period: 'Noite',
    location: 'Restaurante',
  },
  {
    title: 'Fogo no pavio',
    hourStart: '20:40',
    hourEnd: '20:45',
    period: 'Noite',
    location: 'Nave',
    responsible: 'TBD',
  },
  {
    title: 'Noite temática',
    hourStart: '20:45',
    hourEnd: '22:00',
    period: 'Noite',
    location: 'Nave',
    responsible: 'Diego Ayoagi',
  },
  {
    title: 'Teatro',
    hourStart: '22:00',
    hourEnd: '22:20',
    period: 'Noite',
    location: 'Nave',
    responsible: 'Pr. Dudu',
  },
  {
    title: 'Dança',
    hourStart: '22:20',
    hourEnd: '22:30',
    period: 'Noite',
    location: 'Nave',
    responsible: 'Pr. Dudu',
  },
  {
    title: 'Vigília',
    hourStart: '22:30',
    hourEnd: '23:59',
    period: 'Noite',
    location: 'Nave',
    responsible: 'Maite',
  },
];
