export const events = [
  {
    selected: false,
    title: 'Café da manhã',
    hourStart: '08:00',
    hourEnd: '09:40',
    period: 'Manhã',
    location: 'Restaurante',
  },
  {
    selected: false,
    title: 'Abertura',
    hourStart: '09:40',
    hourEnd: '09:45',
    period: 'Manhã',
    location: 'Nave',
    responsible: 'Vídeo boas vindas',
  },
  {
    selected: true,
    title: 'Louvor',
    hourStart: '09:45',
    hourEnd: '10:15',
    period: 'Manhã',
    location: 'Nave',
    responsible: 'Ministério louvor',
  },
  {
    selected: false,
    title: 'Ministração',
    hourStart: '10:15',
    hourEnd: '12:00',
    period: 'Manhã',
    location: 'Nave',
    responsible: 'Sandra Marins',
  },
  {
    selected: false,
    title: 'Almoço',
    hourStart: '12:00',
    hourEnd: '13:30',
    period: 'Tarde',
    location: 'Restaurante',
  },
  {
    selected: false,
    title: 'LIVRE',
    hourStart: '13:30',
    hourEnd: '19:00',
    period: 'Tarde',
  },
  {
    selected: false,
    title: 'Jantar',
    hourStart: '19:00',
    hourEnd: '20:30',
    period: 'Noite',
    location: 'Restaurante',
  },
  {
    selected: false,
    title: 'Fogo no pavio',
    hourStart: '20:40',
    hourEnd: '20:45',
    period: 'Noite',
    location: 'Nave',
    responsible: 'Vídeo boas vindas',
  },
  {
    selected: false,
    title: 'Louvor',
    hourStart: '20:45',
    hourEnd: '21:15',
    period: 'Noite',
    location: 'Nave',
    responsible: 'Ministério louvor',
  },
  {
    selected: false,
    title: 'Ministração',
    hourStart: '21:15',
    hourEnd: '23:00',
    period: 'Noite',
    location: 'Nave',
    responsible: 'Pr. Dudu',
  },
];
