export const eventosSegunda = [
  {
    title: 'Café da manhã',
    hourStart: '08:00',
    hourEnd: '09:40',
    period: 'Manhã',
    location: 'Restaurante',
  },
  {
    title: 'LIVRE',
    hourStart: '09:40',
    hourEnd: '12:00',
    period: 'Manhã',
  },
  {
    title: 'Almoço',
    hourStart: '12:00',
    hourEnd: '13:30',
    period: 'Tarde',
    location: 'Restaurante',
  },
  {
    title: 'LIVRE',
    hourStart: '13:30',
    hourEnd: '15:00',
    period: 'Tarde',
  },
  {
    title: 'Workshop evangelismo',
    hourStart: '15:00',
    hourEnd: '17:00',
    period: 'Tarde',
    location: 'Nave',
    responsible: 'Filipinho',
  },
  {
    title: 'LIVRE',
    hourStart: '17:00',
    hourEnd: '19:00',
    period: 'Tarde',
  },
  {
    title: 'Jantar',
    hourStart: '19:00',
    hourEnd: '20:30',
    period: 'Noite',
    location: 'Restaurante',
  },
  {
    title: 'Fogo no pavio',
    hourStart: '20:40',
    hourEnd: '20:45',
    period: 'Noite',
    location: 'Nave',
    responsible: 'TBD',
  },
  {
    title: 'Louvor',
    hourStart: '20:45',
    hourEnd: '21:15',
    period: 'Noite',
    location: 'Nave',
    responsible: 'Ministério louvor',
  },
  {
    title: 'Ministração',
    hourStart: '21:15',
    hourEnd: '23:00',
    period: 'Noite',
    location: 'Nave',
    responsible: 'Filipinho',
  },
];
