export const eventosTerca = [
  {
    title: 'Café da manhã',
    hourStart: '08:00',
    hourEnd: '09:40',
    period: 'Manhã',
    location: 'Restaurante',
  },
  {
    title: 'Fogo no pavio',
    hourStart: '09:40',
    hourEnd: '09:45',
    period: 'Manhã',
    location: 'Nave',
    responsible: 'TBD',
  },
  {
    title: 'Louvor',
    hourStart: '09:45',
    hourEnd: '10:15',
    period: 'Manhã',
    location: 'Nave',
    responsible: 'Ministério louvor',
  },
  {
    title: 'Ministração',
    hourStart: '10:15',
    hourEnd: '12:00',
    period: 'Manhã',
    location: 'Nave',
    responsible: 'Pr. Danilo Saso',
  },
  {
    title: 'Almoço',
    hourStart: '12:00',
    hourEnd: '13:30',
    period: 'Tarde',
    location: 'Restaurante',
  },
  {
    title: 'TCHAU!',
    hourStart: '13:30',
    hourEnd: '15:00',
    period: 'Tarde',
    location: 'Estacionamento',
  },
];
