export default {
  events: {
    sabado: [
      {
        title: 'Café da manhã',
        hourStart: '08:00',
        hourEnd: '09:40',
        period: 'Manhã',
        location: 'Restaurante',
      },
      {
        title: 'Abertura',
        hourStart: '09:40',
        hourEnd: '09:45',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Vídeo boas vindas',
      },
      {
        title: 'Louvor',
        hourStart: '09:45',
        hourEnd: '10:15',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Ministério louvor',
      },
      {
        title: 'Ministração',
        hourStart: '10:15',
        hourEnd: '12:00',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Pra. Dayane',
      },
      {
        title: 'Almoço',
        hourStart: '12:00',
        hourEnd: '13:30',
        period: 'Tarde',
        location: 'Restaurante',
      },
      {
        title: 'LIVRE',
        hourStart: '13:30',
        hourEnd: '19:00',
        period: 'Tarde',
      },
      {
        title: 'Jantar',
        hourStart: '19:00',
        hourEnd: '20:30',
        period: 'Noite',
        location: 'Restaurante',
      },
      {
        title: 'Fogo no pavio',
        hourStart: '20:40',
        hourEnd: '20:45',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Satoro',
      },
      {
        title: 'Louvor',
        hourStart: '20:45',
        hourEnd: '21:15',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Ministério louvor',
      },
      {
        title: 'Ministração',
        hourStart: '21:15',
        hourEnd: '23:00',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Pr. Marcos',
      },
    ],

    domingo: [
      {
        title: 'Café da manhã',
        hourStart: '08:00',
        hourEnd: '09:40',
        period: 'Manhã',
        location: 'Restaurante',
      },
      {
        title: 'Fogo no pavio',
        hourStart: '09:40',
        hourEnd: '09:45',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Larissa Menezes',
      },
      {
        title: 'Louvor',
        hourStart: '09:45',
        hourEnd: '10:15',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Ministério louvor',
      },
      {
        title: 'Ministração',
        hourStart: '10:15',
        hourEnd: '12:00',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Israel',
      },
      {
        title: 'Almoço',
        hourStart: '12:00',
        hourEnd: '13:30',
        period: 'Tarde',
        location: 'Restaurante',
      },
      {
        title: 'LIVRE',
        hourStart: '13:30',
        hourEnd: '15:00',
        period: 'Tarde',
      },
      {
        title: 'Campeonato Futebol e vôlei',
        hourStart: '15:00',
        hourEnd: '17:00',
        period: 'Tarde',
        location: 'Ginásio poliesportivo',
        responsible: 'Matheus Finochio',
      },
      {
        title: 'LIVRE',
        hourStart: '17:00',
        hourEnd: '19:00',
        period: 'Tarde',
      },
      {
        title: 'Jantar',
        hourStart: '19:00',
        hourEnd: '20:30',
        period: 'Noite',
        location: 'Restaurante',
      },
      {
        title: 'Noite temática',
        hourStart: '20:40',
        hourEnd: '22:00',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Diego Ayoagi',
      },
      {
        title: 'Teatro',
        hourStart: '22:00',
        hourEnd: '22:20',
        period: 'Noite',
        location: 'Nave',
      },
      {
        title: 'Dança',
        hourStart: '22:20',
        hourEnd: '22:30',
        period: 'Noite',
        location: 'Nave',
      },
      {
        title: 'Vigília',
        hourStart: '22:30',
        hourEnd: '23:59',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Maite',
      },
    ],

    segunda: [
      {
        title: 'Café da manhã',
        hourStart: '08:00',
        hourEnd: '09:40',
        period: 'Manhã',
        location: 'Restaurante',
      },
      {
        title: 'LIVRE',
        hourStart: '09:40',
        hourEnd: '12:00',
        period: 'Manhã',
      },
      {
        title: 'Almoço',
        hourStart: '12:00',
        hourEnd: '13:30',
        period: 'Tarde',
        location: 'Restaurante',
      },
      {
        title: 'LIVRE',
        hourStart: '13:30',
        hourEnd: '15:00',
        period: 'Tarde',
      },
      {
        title: 'Workshop evangelismo',
        hourStart: '15:00',
        hourEnd: '17:00',
        period: 'Tarde',
        location: 'Nave',
        responsible: 'Filipe Matheus',
      },
      {
        title: 'LIVRE',
        hourStart: '17:00',
        hourEnd: '19:00',
        period: 'Tarde',
      },
      {
        title: 'Jantar',
        hourStart: '19:00',
        hourEnd: '20:30',
        period: 'Noite',
        location: 'Restaurante',
      },
      {
        title: 'Fogo no pavio',
        hourStart: '20:40',
        hourEnd: '20:45',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Arthur',
      },
      {
        title: 'Louvor',
        hourStart: '20:45',
        hourEnd: '21:15',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Ministério louvor',
      },
      {
        title: 'Ministração',
        hourStart: '21:15',
        hourEnd: '23:00',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Filipe Matheus',
      },
    ],

    terca: [
      {
        title: 'Café da manhã',
        hourStart: '08:00',
        hourEnd: '09:40',
        period: 'Manhã',
        location: 'Restaurante',
      },
      {
        title: 'Fogo no pavio',
        hourStart: '09:40',
        hourEnd: '09:45',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Kevin Marcondes',
      },
      {
        title: 'Louvor',
        hourStart: '09:45',
        hourEnd: '10:15',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Ministério louvor',
      },
      {
        title: 'Ministração',
        hourStart: '10:15',
        hourEnd: '12:00',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Pr. Danilo Saso',
      },
      {
        title: 'Almoço',
        hourStart: '12:00',
        hourEnd: '13:30',
        period: 'Tarde',
        location: 'Restaurante',
      },
      {
        title: 'TCHAU!',
        hourStart: '13:30',
        hourEnd: '15:00',
        period: 'Tarde',
        location: 'Estacionamento',
      },
    ],
  },
};
