export default {
  events: {
    sabado: [
      {
        title: 'Café da manhã',
        hourStart: '08:00',
        hourEnd: '09:40',
        period: 'Manhã',
        location: 'Restaurante',
      },
      {
        title: 'Abertura',
        hourStart: '09:40',
        hourEnd: '09:45',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Vídeo boas vindas',
      },
      {
        title: 'Louvor',
        hourStart: '09:45',
        hourEnd: '10:15',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Ministério louvor',
      },
      {
        title: 'Ministração',
        hourStart: '10:15',
        hourEnd: '12:00',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Pra. Dayane',
      },
      {
        title: 'Almoço',
        hourStart: '12:00',
        hourEnd: '13:30',
        period: 'Tarde',
        location: 'Restaurante',
      },
      {
        title: 'LIVRE',
        hourStart: '13:30',
        hourEnd: '19:00',
        period: 'Tarde',
      },
      {
        title: 'Jantar',
        hourStart: '19:00',
        hourEnd: '20:30',
        period: 'Noite',
        location: 'Restaurante',
      },
      {
        title: 'Fogo no pavio',
        hourStart: '20:40',
        hourEnd: '20:45',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Satoro',
      },
      {
        title: 'Louvor',
        hourStart: '20:45',
        hourEnd: '21:15',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Ministério louvor',
      },
      {
        title: 'Ministração',
        hourStart: '21:15',
        hourEnd: '23:00',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Pr. Marcos',
      },
    ],

    domingo: [
      {
        title: 'Café da manhã',
        hourStart: '08:00',
        hourEnd: '09:40',
        period: 'Manhã',
        location: 'Restaurante',
      },
      {
        title: 'Fogo no pavio',
        hourStart: '09:40',
        hourEnd: '09:45',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Larissa Menezes',
      },
      {
        title: 'Louvor',
        hourStart: '09:45',
        hourEnd: '10:15',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Ministério louvor',
      },
      {
        title: 'Ministração',
        hourStart: '10:15',
        hourEnd: '12:00',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Israel',
      },
      {
        title: 'Almoço',
        hourStart: '12:00',
        hourEnd: '13:30',
        period: 'Tarde',
        location: 'Restaurante',
      },
      {
        title: 'LIVRE',
        hourStart: '13:30',
        hourEnd: '14:00',
        period: 'Tarde',
      },
      {
        title: 'Campeonato vôlei',
        hourStart: '14:00',
        hourEnd: '14:30',
        period: 'Tarde',
        location: 'Ginásio poliesportivo',
        game: 'Jogo 1',
        time1: 'Time 7',
        participantes1: ['Ana Caroline Andrade', 'Enzo Nery', 'Guilherme de Carvalho ', 'Hosana', 'Oséas Fernandes', 'Pedro Cruseiro'],
        time2: 'Time 9',
        participantes2: ['Giovanna Benísia', 'Karina Paes', 'Lenara Campelo', 'Mateus Ribeiro', 'Pedro Freire', 'Vanderson Durães'],
      },
      {
        title: 'Campeonato vôlei',
        hourStart: '14:30',
        hourEnd: '15:00',
        period: 'Tarde',
        location: 'Ginásio poliesportivo',
        game: 'Jogo 2',
        time1: 'Time 3',
        participantes1: ['Davi Marins Souza', 'Felps', 'Giovanna Bárbara Ribeiro', 'Lucas Cecílio', 'Matheus Ribeiro', 'Victor Huna'],
        time2: 'Time 10',
        participantes2: ['Camila', 'Dani', 'Renato', 'Rodrigo ', 'Weslei ', 'Zelo'],
      },
      {
        title: 'Campeonato vôlei',
        hourStart: '15:00',
        hourEnd: '15:30',
        period: 'Tarde',
        location: 'Ginásio poliesportivo',
        game: 'Jogo 3',
        time1: 'Time 4',
        participantes1: ['James', 'Khin Borges', 'Lucas Zocchio', 'Pietra', 'Tiago Cirillo', 'Vini Sena'],
        time2: 'Time 5',
        participantes2: ['Amanda Dias', 'João Fernando Vezaro', 'Luma Porto', 'Victor Porto', 'Vinicius Porto', 'Yasmin Lima Silva'],
      },
      {
        title: 'Campeonato vôlei',
        hourStart: '15:30',
        hourEnd: '16:00',
        period: 'Tarde',
        location: 'Ginásio poliesportivo',
        game: 'Jogo 4',
        time1: 'Time 1',
        participantes1: ['Beatriz Luna', 'Daniele Mendonça', 'Marco Carvalho ', 'Maria Luiza Baltazar', 'Re Saso', 'Vitória Martins'],
        time2: 'Vencedor Jogo 1',
      },
      {
        title: 'Campeonato vôlei',
        hourStart: '16:00',
        hourEnd: '16:30',
        period: 'Tarde',
        location: 'Ginásio poliesportivo',
        game: 'Jogo 5',
        time1: 'Time 2',
        participantes1: ['Bibi', 'Cacau', 'Caio', 'Camilla', 'Gabs', 'Lucas de Oliveira'],
        time2: 'Time 8',
        participantes2: ['Dudu', 'Fabio', 'Giulia Gueicha de Oliveira', 'Isabela Alves Frazao', 'Jeff', 'Tico'],
      },
      {
        title: 'Campeonato vôlei',
        hourStart: '16:30',
        hourEnd: '17:00',
        period: 'Tarde',
        location: 'Ginásio poliesportivo',
        game: 'Jogo 6',
        time1: 'Time 6',
        participantes1: ['André Gustavo', 'Caio', 'Gabriel Dias', 'Gabriel popeta', 'Jaqueline', 'Murilo'],
        time2: 'Vencedor Jogo 2',
      },
      {
        title: 'Campeonato vôlei',
        hourStart: '16:00',
        hourEnd: '16:30',
        period: 'Tarde',
        location: 'Ginásio poliesportivo',
        game: 'Jogo 7',
        time1: 'Vencedor Jogo 3',
        time2: 'Vencedor Jogo 4',
      },
      {
        title: 'Campeonato vôlei',
        hourStart: '16:30',
        hourEnd: '17:00',
        period: 'Tarde',
        location: 'Ginásio poliesportivo',
        game: 'Jogo 8',
        time1: 'Vencedor Jogo 5',
        time2: 'Vencedor Jogo 6',
      },
      {
        title: 'Campeonato vôlei',
        hourStart: '17:00',
        hourEnd: '17:30',
        period: 'Tarde',
        location: 'Ginásio poliesportivo',
        game: 'FINAL',
        time1: 'Vencedor Jogo 7',
        time2: 'Vencedor Jogo 8',
      },
      {
        title: 'LIVRE',
        hourStart: '17:30',
        hourEnd: '19:00',
        period: 'Tarde',
      },
      {
        title: 'Jantar',
        hourStart: '19:00',
        hourEnd: '20:30',
        period: 'Noite',
        location: 'Restaurante',
      },
      {
        title: 'Noite temática',
        hourStart: '20:40',
        hourEnd: '22:00',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Diego Ayoagi',
      },
      {
        title: 'Teatro',
        hourStart: '22:00',
        hourEnd: '22:20',
        period: 'Noite',
        location: 'Nave',
      },
      {
        title: 'Dança',
        hourStart: '22:20',
        hourEnd: '22:30',
        period: 'Noite',
        location: 'Nave',
      },
      {
        title: 'Vigília',
        hourStart: '22:30',
        hourEnd: '23:59',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Maite',
      },
    ],

    segunda: [
      {
        title: 'Café da manhã',
        hourStart: '08:00',
        hourEnd: '09:40',
        period: 'Manhã',
        location: 'Restaurante',
      },
      {
        title: 'LIVRE',
        hourStart: '09:40',
        hourEnd: '12:00',
        period: 'Manhã',
      },
      {
        title: 'Almoço',
        hourStart: '12:00',
        hourEnd: '13:30',
        period: 'Tarde',
        location: 'Restaurante',
      },
      {
        title: 'LIVRE',
        hourStart: '13:30',
        hourEnd: '15:00',
        period: 'Tarde',
      },
      {
        title: 'Workshop evangelismo',
        hourStart: '15:00',
        hourEnd: '17:00',
        period: 'Tarde',
        location: 'Nave',
        responsible: 'Filipe Matheus',
      },
      {
        title: 'LIVRE',
        hourStart: '17:00',
        hourEnd: '19:00',
        period: 'Tarde',
      },
      {
        title: 'Jantar',
        hourStart: '19:00',
        hourEnd: '20:30',
        period: 'Noite',
        location: 'Restaurante',
      },
      {
        title: 'Fogo no pavio',
        hourStart: '20:40',
        hourEnd: '20:45',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Arthur',
      },
      {
        title: 'Louvor',
        hourStart: '20:45',
        hourEnd: '21:15',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Ministério louvor',
      },
      {
        title: 'Ministração',
        hourStart: '21:15',
        hourEnd: '23:00',
        period: 'Noite',
        location: 'Nave',
        responsible: 'Filipe Matheus',
      },
    ],

    terca: [
      {
        title: 'Café da manhã',
        hourStart: '08:00',
        hourEnd: '09:40',
        period: 'Manhã',
        location: 'Restaurante',
      },
      {
        title: 'Fogo no pavio',
        hourStart: '09:40',
        hourEnd: '09:45',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Kevin Marcondes',
      },
      {
        title: 'Louvor',
        hourStart: '09:45',
        hourEnd: '10:15',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Ministério louvor',
      },
      {
        title: 'Ministração',
        hourStart: '10:15',
        hourEnd: '12:00',
        period: 'Manhã',
        location: 'Nave',
        responsible: 'Pr. Danilo Saso',
      },
      {
        title: 'Almoço',
        hourStart: '12:00',
        hourEnd: '13:30',
        period: 'Tarde',
        location: 'Restaurante',
      },
      {
        title: 'TCHAU!',
        hourStart: '13:30',
        hourEnd: '15:00',
        period: 'Tarde',
        location: 'Estacionamento',
      },
    ],
  },
};
